### ISSUE TITLE
Enhancement: Use Marker as PDF Parsing Tool in Post-Processing Pipeline

### ISSUE THREAD

**Issue by Ma-Yongqiang** [neuralwork/arxiver#1]
The current post-processing setup is fantastic. It’s well-structured and does a great job validating and cleaning up the Nougat output.

However, to enhance the reliability and accuracy of PDF parsing, I recommend replacing or supplementing the existing method with [Marker](https://github.com/VikParuchuri/marker), a dedicated PDF parsing tool. This tool could improve page extraction consistency and streamline the post-processing workflow.

It could be a nice addition to an already strong pipeline.

**Comment by alaradirik** [comment]
Thanks for the suggestion @Ma-Yongqiang! We have open-sourced this repository mainly as the source code of the [arxiver](https://huggingface.co/datasets/neuralwork/arxiver) dataset but we might create a separate branch or repo for more advanced pdf processing
